### ISSUE TITLE
Error when using image_512_cc.yml

### ISSUE THREAD

**Issue by mateibejan1** [bahjat-kawar/ddrm#8]
I've tested you model on all available configurations in Google Colab and got this when running image_512_cc.yml.

```
Error when using image_256_cc.yml #7
ERROR - main.py - 2022-07-21 11:16:31,872 - Traceback (most recent call last):
  File "main.py", line 164, in main
    runner.sample()
  File "/content/ddrm/runners/diffusion.py", line 135, in sample
    model.load_state_dict(torch.load(ckpt, map_location=self.device))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xef'.
```

Could you recommend a possible fix?

**Comment by jiamings** [comment]
I suspect this is due to the pickle file not being downloaded properly.

**Comment by mateibejan1** [comment]
I've tested it locally and the problem persists, so it isn't related to Colab's I/O throughput.

**Comment by mateibejan1** [comment]
Found the source of this behaviour: a code in `/runners/diffusion.py` at line 128: https://github.com/bahjat-kawar/ddrm/blob/73fbbef09a23889401a67ca616aa283a3820d849/runners/diffusion.py#L128. Instead of downloading the class-conditioned conditioned diffusion checkpoint, you download the unconditional one.
